version: '3.7'

services:
  db:
    image: mariadb:10.4
    restart: always
    env_file:
      - db.env
    volumes:
      - db-data:/var/lib/mysql

  app:
    depends_on:
      - db
    build: .
    # Wait for the database to spin up first if the app is started using Docker Compose.
    command: wait-for-it.sh db:3306 -t 30 -s -- python3 ./pyarcade/start.py
    # Use an interactive session for the terminal-based GUI.
    tty: true
    stdin_open: true

volumes:
  db-data:

#networks:
