version: '3.7'

services:
  db:
    image: mariadb:10.4
    restart: always
    env_file:
      - db.env
    # volumes:
    #   - db-data:/var/lib/mysql
    logging:
      driver: none

  app:
    depends_on:
      - db
    environment:
      FLASK_APP: "pyarcade/start:create_app()"
      FLASK_ENV: "production"
    build:
      context: .
    ports:
      - 5000:5000
    # Wait for the database to spin up first if the app is started using Docker Compose.
    command: wait-for-it.sh db:3306 -t 30 -s -- flask run --host=0.0.0.0
    logging:
      driver: none

# volumes:
#   db-data:

#networks:
