version: '3.7'

# To run api: docker-compose -f pyarcade_deploy.yml up

services:
  db:
    image: mariadb:10.4
    restart: always
    env_file:
      - db.env

  pyarcade:
    image: pyarcade:app
    depends_on:
      - db
    environment:
      FLASK_APP: "pyarcade/api:create_app()"
      FLASK_ENV: "production"
    ports:
      - 5000:5000
    command: ["wait-for-it.sh", "database:3306", "-t", "30", "--", "flask", "run", "--host=0.0.0.0"]
