version: '3.7'

services:
  db:
    image: mariadb:10.4
    env_file:
      - db.env

  pyarcade:
    depends_on:
      - db
    build:
      context: .
    environment:
      - FLASK_APP=pyarcade/start
      - FLASK_ENV=development
    command: wait-for-it.sh database:3306 -t 120 -s -- python setup.py test
